USE CITIZENCONNECT;

CREATE TABLE Roles (
  RoleID INT PRIMARY KEY,
  RoleName VARCHAR(255) NOT NULL
);

CREATE TABLE Users (
  Id INT PRIMARY KEY,
  Username VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL, 
  RoleID INT, 
  isDeleted INT DEFAULT 0,
  isEmailSent INT DEFAULT 0,
  FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
);